spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G9Z9J5nDBngEXEqnquj
      secret-key: CG6Dy17G3OdAOowi556d7IiEclMMLi
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-oss01
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appcode: c6ebcb445e0241f5b699640b2f7e2e5c

  application:
    name: gulimall-third-party
server:
  port: 9656
